[package]
name = "pen-ffi-macro"
description = "FFI macro library for Pen programming language"
version = "0.5.2"
publish = true
edition = "2024"
license = "MIT"
repository = "https://github.com/pen-lang/pen"

[lib]
proc-macro = true

[dependencies]
convert_case = "0.11.0"
proc-macro2 = "1.0.107"
quote = "1.0.47"
syn = { version = "3.0.3", features = ["full"] }

[dev-dependencies]
pen-ffi = { path = "../ffi", features = ["runtime"] }
