[package]
name = "pen-ffi-macro"
version = "0.5.2"
edition = "2024"
description = "FFI macro library for Pen programming language"
repository = "https://github.com/pen-lang/pen"
license = "MIT"
publish = true

[lib]
proc-macro = true

[dependencies]
convert_case = "0.12.0"
proc-macro2 = "1.0.107"
quote = "1.0.47"
syn = { version = "3.0.3", features = ["full"] }

[dev-dependencies]
pen-ffi = { path = "../ffi", features = ["runtime"] }
