[package]
name = "format"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
ast = { path = "../ast" }
bumpalo = { version = "3.20.3", features = ["allocator-api2"] }
itertools = "0.15.0"
mfmt = "0.4.2"
position = { path = "../position" }

[dev-dependencies]
indoc = "2.0.7"
pretty_assertions = "1.4.1"
