version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: daily
  - package-ecosystem: bundler
    directory: /
    schedule:
      interval: daily
  - package-ecosystem: npm
    directory: /doc
    schedule:
      interval: daily
  - package-ecosystem: rust-toolchain
    directories:
      - /
      - /packages/core/ffi
      - /packages/http/ffi
      - /packages/json/ffi
      - /packages/os-sync/ffi
      - /packages/os/ffi/application
      - /packages/os/ffi/library
      - /packages/prelude/ffi
      - /packages/sql/ffi
    groups:
      rust-toolchain:
        group-by: dependency-name
        patterns:
          - "*"
    schedule:
      interval: daily
  - package-ecosystem: uv
    directory: /doc
    schedule:
      interval: daily
  - package-ecosystem: cargo
    directory: /
    schedule:
      interval: daily
  - package-ecosystem: cargo
    directory: /cmd/test
    schedule:
      interval: daily
  - package-ecosystem: cargo
    directory: /packages/core/ffi
    schedule:
      interval: daily
  - package-ecosystem: cargo
    directory: /packages/html/ffi
    schedule:
      interval: daily
  - package-ecosystem: cargo
    directory: /packages/http/ffi
    schedule:
      interval: daily
  - package-ecosystem: cargo
    directory: /packages/json/ffi
    schedule:
      interval: daily
  - package-ecosystem: cargo
    directory: /packages/os-sync/ffi
    schedule:
      interval: daily
  - package-ecosystem: cargo
    directory: /packages/os/ffi/application
    schedule:
      interval: daily
  - package-ecosystem: cargo
    directory: /packages/os/ffi/library
    schedule:
      interval: daily
  - package-ecosystem: cargo
    directory: /packages/prelude/ffi
    schedule:
      interval: daily
  - package-ecosystem: cargo
    directory: /packages/random/ffi
    schedule:
      interval: daily
  - package-ecosystem: cargo
    directory: /packages/regex/ffi
    schedule:
      interval: daily
  - package-ecosystem: cargo
    directory: /packages/sql/ffi
    schedule:
      interval: daily
  - package-ecosystem: cargo
    directory: /packages/test/ffi
    schedule:
      interval: daily
