pull_request_rules:
  - name: dependabot
    conditions:
      - author=dependabot[bot]
    actions:
      merge:
        method: squash
  - name: auto-merge
    conditions:
      - label=auto-merge
    actions:
      merge:
        method: squash
        strict: smart
