pull_request_rules:
  - name: dependabot
    conditions:
      - author=dependabot[bot]
    actions:
      merge:
        method: squash
        strict: smart
  - name: auto-merge
    conditions:
      - label=merge
      - or:
          - author=raviqqe
          - "#approved-reviews-by>=1"
    actions:
      queue:
        name: default
        method: squash
        commit_message: title+body
queue_rules:
  - name: default
    conditions: []
