name: pen/setup
description: Sets up a build environment
inputs: {}
outputs: {}
runs:
  using: composite
  steps:
    - uses: ruby/setup-ruby@3ff19f5e2baf30647122352b96108b1fbe250c64 # v1.299.0
    - uses: raviqqe/cargo-cache@98cf6adfd93fe558bc3ae1735b97f10998f2067f # v1.0.3
    - uses: raviqqe/enable-homebrew@a1458a466e3f3218b534472496fa03adb2926204 # v1.0.3
      with:
        stable: true
    - run: tools/ci/github/setup.sh
      shell: bash
