[package]
name = "os"
version = "0.1.0"
publish = false
edition = "2021"

[lib]
crate-type = ["staticlib"]

[dependencies]
ffi = { package = "pen-ffi", version = "0.3" }
once_cell = "1"
rand = "0.8"
# Feature flags of tokio must match the ones in the application crate for its
# object files to be considered from the same crate.
tokio = { version = "1", features = ["full"] }
