[package]
name = "os"
version = "0.1.0"
publish = false
edition.workspace = true

[lib]
crate-type = ["staticlib"]

[dependencies]
ffi = { package = "pen-ffi", version = "*", features = ["runtime", "std"] }
futures = "0.3"
tokio = { version = "1", features = ["full"] }
