[toolchain]
channel = "stable"
components = ["clippy", "rustfmt", "rust-analyzer", "rust-src"]
targets = [
  "i686-unknown-linux-musl",
  "x86_64-unknown-linux-musl",
  "aarch64-unknown-linux-musl",
  "wasm32-wasip2",
]
