mod build_script_compiler;
mod build_script_dependency_compiler;
mod external_package_initializer;
mod file_path;
mod file_path_configuration;
mod file_path_displayer;
mod file_system;
mod infrastructure;
mod main_module_target;
mod module_builder;
mod module_target;
mod package_configuration;
mod package_configuration_reader;

pub use build_script_compiler::*;
pub use build_script_dependency_compiler::*;
pub use external_package_initializer::*;
pub use file_path::*;
pub use file_path_configuration::*;
pub use file_path_displayer::*;
pub use file_system::*;
pub use infrastructure::*;
pub use main_module_target::*;
pub use module_builder::*;
pub use module_target::*;
pub use package_configuration::*;
pub use package_configuration_reader::*;

pub const EXTERNAL_PACKAGE_DIRECTORY: &str = "packages";
pub const OBJECT_DIRECTORY: &str = "objects";
