[package]
name = "parse"
version = "0.1.0"
publish = false
authors = ["Yota Toyama <raviqqe@gmail.com>"]
edition = "2024"

[dependencies]
ast = { path = "../ast" }
nom = "8.0.0"
nom-language = "0.1.0"
nom_locate = "5.0.0"
position = { path = "../position" }

[dev-dependencies]
indoc = "2.0.7"
insta = "1.41.1"
pretty_assertions = "1.4.1"
