[book]
authors = ["Yota Toyama"]
language = "en"
multilingual = false
src = "src"
title = "Pen programming language"

[build]
create-missing = false

[output.html]
cname = "pen-lang.org"
git-repository-url = "https://github.com/pen-lang/pen"
edit-url-template = "https://github.com/pen-lang/pen/edit/main/doc/{path}"
google-analytics = "285447751"

[output.html.print]
enable = false
