[book]
authors = ["Yota Toyama"]
language = "en"
multilingual = false
src = "src"
title = "Pen"

[build]
create-missing = false

[output.html]
cname = "pen-lang.org"

[output.html.fold]
enable = true
