[book]
authors = ["Yota Toyama"]
language = "en"
multilingual = false
src = "src"
title = "Pen programming language"
description = "The programming language for scalable development"

[build]
create-missing = false

[preprocessor.pagetoc]

[output.html]
default-theme = "rust"
preferred-dark-theme = "navy"
additional-css = ["theme/pagetoc.css"]
additional-js = ["theme/pagetoc.js", "theme/custom-highlight.js"]
cname = "pen-lang.org"
git-repository-url = "https://github.com/pen-lang/pen"
edit-url-template = "https://github.com/pen-lang/pen/edit/main/doc/{path}"
