[package]
name = "mir-fmm"
version = "0.1.0"
edition = "2024"
description = "MIR to F-- compiler"
license = "MIT"
publish = false

[dependencies]
fmm = { git = "https://github.com/raviqqe/fmm", branch = "main" }
fnv = "1.0.7"
mir = { path = "../mir" }
plist = { git = "https://github.com/raviqqe/plist-rs", branch = "main" }

[dev-dependencies]
fmm-c = { git = "https://github.com/raviqqe/fmm", branch = "main" }
fmm-llvm = { git = "https://github.com/raviqqe/fmm", branch = "main" }
insta = "1.41.1"
tempfile = "3.27.0"
