[package]
name = "pen-ffi"
version = "0.10.26"
edition = "2024"
description = "FFI library for Pen programming language"
repository = "https://github.com/pen-lang/pen"
license = "MIT"
publish = true

[dependencies]
async-stream = "0.3.6"
futures = "0.3.34"
pen-ffi-macro = { path = "../ffi-macro", version = "0.5.2" }
tokio = { version = "1.53.1", features = ["rt-multi-thread"], optional = true }

[dev-dependencies]
tokio = { version = "1.53.1", features = ["macros", "rt"] }

[features]
runtime = ["std", "tokio"]
std = []
