[package]
name = "regex"
version = "0.1.0"
publish = false
edition = "2021"

[lib]
crate-type = ["staticlib"]

[dependencies]
ffi = { package = "pen-ffi", version = "*", features = ["std"] }
regex = "1"
