pub mod boolean_operation_transformer;
mod collection_type_transformer;
pub mod equal_operation_transformer;
mod hash_calculation_transformer;
pub mod if_list_transformer;
pub mod if_map_transformer;
pub mod list_literal_transformer;
mod map_context_transformer;
pub mod map_literal_transformer;
pub mod not_equal_operation_transformer;
pub mod record_equal_function_transformer;
pub mod record_hash_function_transformer;
mod record_type_information_compiler;
