pub mod boolean_operation;
mod collection_type;
pub mod equal_operation;
mod hash_calculation;
pub mod if_list;
pub mod if_map;
pub mod list_literal;
pub mod map_context;
pub mod map_literal;
pub mod not_equal_operation;
pub mod record_equal_function;
pub mod record_hash_function;
mod record_type_information;
