name: benchmark
on:
  push:
    branches:
      - main
  pull_request:
  merge_group:
concurrency:
  group: benchmark-${{ github.ref }}
  cancel-in-progress: true
jobs:
  benchmark:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - uses: ./.github/actions/setup
      - run: tools/build.sh
      - run: tools/benchmark.sh -b
      - run: tools/benchmark.sh
