name: benchmark
on:
  push:
    branches:
      - main
  pull_request:
  merge_group:
concurrency:
  group: benchmark-${{ github.ref }}
  cancel-in-progress: true
jobs:
  benchmark:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./tools/ci/github/setup
      - run: tools/build.sh
      - run: tools/benchmark.sh -b
      - run: tools/benchmark.sh
