name: benchmark
on:
  push:
    branches:
      - main
  pull_request:
  merge_group:
concurrency:
  group: benchmark-${{ github.ref }}
  cancel-in-progress: true
jobs:
  benchmark:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: ./.github/actions/setup
      - run: tools/build.sh
      - run: tools/benchmark.sh -b
      - run: tools/benchmark.sh
