name: benchmark
on:
  push:
    branches:
      - main
  pull_request:
  merge_group:
concurrency:
  group: benchmark-${{ github.ref }}
  cancel-in-progress: true
jobs:
  benchmark:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - uses: ./.github/actions/setup
      - run: tools/build.sh
      - run: tools/benchmark.sh -b
      - run: tools/benchmark.sh
