name: document
on:
  push:
    branches:
      - main
  pull_request:
  merge_group:
jobs:
  document:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: homebrew/actions/setup-homebrew@master
      - run: tools/ci/github/setup.sh
      - run: tools/document/build.sh
      - uses: peaceiris/actions-gh-pages@v4
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: doc/site
