name: homebrew
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: Homebrew/actions/setup-homebrew@master
      - run: brew tap pen-lang/pen .
      - run: brew install pen-lang/pen/pen
      - run: brew test pen-lang/pen/pen
