name: release
on:
  push:
    branches:
      - main
  pull_request:
  merge_group:
concurrency:
  group: release-${{ github.ref }}
  cancel-in-progress: true
jobs:
  tag_check:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ env.version }}
      should_release: ${{ env.should_release }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - run: echo version=$(tools/version.sh) >> $GITHUB_ENV
      - run: |
          git fetch --prune --unshallow --tags

          if [ ${{ github.ref }} = 'refs/heads/main' ] && ! git tag | grep v$version; then
            echo should_release=true >> $GITHUB_ENV
          fi
  build_asset:
    needs: tag_check
    strategy:
      matrix:
        os:
          - ubuntu-24.04
          - macos-15
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: ./.github/actions/setup
      - run: echo asset=$(tools/build_asset.sh) >> $GITHUB_ENV
      - uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6.0.0
        with:
          name: ${{ env.asset }}
          path: ${{ env.asset }}
  github:
    needs:
      - tag_check
      - build_asset
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0
      - run: git log --pretty='- %s by %aN' $(git describe --tags --abbrev=0 HEAD^)..HEAD > changes.md
      - uses: actions/download-artifact@70fc10c6e5e1ce46ad2ea6f2b72d43f7d47b13c3 # v8.0.0
        with:
          path: artifacts
      - uses: softprops/action-gh-release@153bb8e04406b158c6c84fc1615b65b24149a1fe # v2.6.1
        if: needs.tag_check.outputs.should_release == 'true'
        with:
          tag_name: v${{ needs.tag_check.outputs.version }}
          body_path: changes.md
          files: artifacts/**
          fail_on_unmatched_files: true
  homebrew:
    needs:
      - tag_check
      - github
    if: needs.tag_check.outputs.should_release == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          repository: pen-lang/homebrew-pen
      - run: |
          file=Formula/pen.rb
          version=${{ needs.tag_check.outputs.version }}
          hash=$(curl -fsSL https://github.com/pen-lang/pen/archive/refs/tags/v$version.tar.gz | sha256sum | cut -f 1 -d ' ')

          sed -i "s/v[[0-9.]*.tar.gz/v$version.tar.gz/" $file
          sed -i "s/^  sha256 .*/  sha256 \"$hash\"/" $file
          sed -i /revision/d $file
      - uses: peter-evans/create-pull-request@c0f553fe549906ede9cf27b5156039d195d2ece0 # v8.1.0
        with:
          title: Bump version
          branch: chore/version
          token: ${{ secrets.PR_CREATION_TOKEN }}
  release:
    needs:
      - tag_check
      - build_asset
      - github
      - homebrew
    if: always()
    runs-on: ubuntu-latest
    steps:
      - run: for result in ${{ join(needs.*.result, ' ') }}; do [ $result = success -o $result = skipped ]; done
