name: test
on:
  push:
    branches:
      - main
  pull_request:
  merge_group:
concurrency:
  group: test-${{ github.ref }}
  cancel-in-progress: true
env:
  HOMEBREW_NO_AUTO_UPDATE: "1"
jobs:
  build:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      - uses: ./tools/ci/github/setup
      - run: tools/build.sh
      - run: git diff --exit-code
      - uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6.0.0
        with:
          name: build-${{ matrix.os }}
          path: target/release/pen
  unit_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      - uses: ./tools/ci/github/setup
      - run: tools/unit_test.sh
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      - uses: ./tools/ci/github/setup
      - run: tools/coverage.sh
      - uses: codecov/codecov-action@75cd11691c0faa626561e295848008c8a7dddffe # v5.5.4
        with:
          files: lcov.info
  feature_test:
    needs: build
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
        index: [0, 1, 2, 3, 4, 5, 6, 7]
        total: [8]
        exclude:
          - os: ${{ github.ref == 'refs/heads/main' && 'none' || 'macos-latest' }}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      - uses: ./tools/ci/github/setup
      - uses: actions/download-artifact@70fc10c6e5e1ce46ad2ea6f2b72d43f7d47b13c3 # v8.0.0
        with:
          name: build-${{ matrix.os }}
          path: target/release
      - run: chmod +x target/release/pen
      - run: tools/integration_test.sh $(find features -name *.feature | sort | awk 'NR % ${{ matrix.total }} == ${{ matrix.index }}')
  test:
    needs:
      - build
      - unit_test
      - coverage
      - feature_test
    if: always()
    runs-on: ubuntu-latest
    steps:
      - run: for result in ${{ join(needs.*.result, ' ') }}; do [ $result = success ]; done
